apiVersion: v1
kind: Service
metadata:
  name: {{ include "agile-app.fullname" . }}-backend
  labels:
    {{- include "agile-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 3001
      protocol: TCP
      name: backend
  selector:
    app: {{ include "agile-app.fullname" . }}-backend 